name: Publish Docker

on:
  push:
    branches: [ main ]
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: bounds/siwe_oidc
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true
        tag_semver: true
        snapshot: true
